name: Deploy to Google Play

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.5'
          channel : 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Restore keystore from base64
        run: |
          mkdir -p android/app
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > android/app/upload-keystore.jks
          
      - name: Create key.properties
        run: |
          cat << EOF > android/key.properties
          storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}
          keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}
          storeFile=upload-keystore.jks
          EOF
          
      - name: Build appbundle
        run: flutter build appbundle --release
        
      - name: List build outputs (debug)
        run: |
          echo "PWD=$(pwd)"
          ls -R build/app/outputs/bundle || echo "No bundle folder"

      - name: Upload to Google Play (Open testing)
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT }}
          packageName: com.wanto.logistiscout
          releaseFiles: build/app/outputs/bundle/release/*.aab
          track: open
          status: completed
